export const tempNewsData = {
  "Six more": [
    {
      word: "Shastri Nagar",
      spans: [
        {
          start: 547,
          end: 560,
        },
      ],
      country_predicted: "IND",
      country_conf: 0.89529574,
      geo: {
        admin1: "Rajasthan",
        lon: "75.802342",
        lat: "26.9469",
        country_code3: "IND",
        geonameid: "10521059",
        place_name: "Shāstri Nagar",
        feature_class: "P",
        feature_code: "PPL",
      },
    },
    {
      word: "Sindhi Camp",
      spans: [
        {
          start: 957,
          end: 968,
        },
      ],
      country_predicted: "IND",
      country_conf: 0.89529574,
      geo: {
        admin1: "Rajasthan",
        lon: "75.800011",
        lat: "26.924483",
        country_code3: "IND",
        geonameid: "10525219",
        place_name: "Sindhi Camp",
        feature_class: "P",
        feature_code: "PPL",
      },
    },
  ],
  "The sani": [
    {
      word: "Mansarovar",
      spans: [{ start: 308, end: 318 }],
      country_predicted: "IND",
      country_conf: 0.9528109,
      geo: {
        admin1: "Rajasthan",
        lat: "26.85445",
        lon: "75.76125",
        country_code3: "IND",
        geonameid: "10245951",
        place_name: "Hotel Mansarovar Palace",
        feature_class: "S",
        feature_code: "HTL",
      },
    },
    {
      word: "Kalwar Road",
      spans: [{ start: 788, end: 799 }],
      country_predicted: "IND",
      country_conf: 0.90487736,
      geo: {
        admin1: "Rajasthan",
        lat: "26.9883",
        lon: "75.5846",
        country_code3: "IND",
        geonameid: "10941336",
        place_name: "Karwār Road",
        feature_class: "R",
        feature_code: "RD",
      },
    },
    {
      word: "Vaishali Nagar",
      spans: [{ start: 818, end: 832 }],
      country_predicted: "IND",
      country_conf: 0.9637409,
      geo: {
        admin1: "Rajasthan",
        lat: "26.91258",
        lon: "75.74412",
        country_code3: "IND",
        geonameid: "7302171",
        place_name: "Vaishali Nagar",
        feature_class: "P",
        feature_code: "PPL",
      },
    },
  ],
  "For some": [
    {
      word: "Sudarshanpura",
      spans: [{ start: 278, end: 291 }],
      country_predicted: "IND",
      country_conf: 0.9528109,
      geo: {
        admin1: "Rajasthan",
        lat: "26.8959",
        lon: "75.7902",
        country_code3: "IND",
        geonameid: "10510009",
        place_name: "Sudarshanpur",
        feature_class: "P",
        feature_code: "PPL",
      },
    },
    {
      word: "Ajmer",
      spans: [{ start: 406, end: 411 }],
      country_predicted: "IND",
      country_conf: 0.90487736,
      geo: {
        admin1: "Rajasthan",
        lat: "26.25",
        lon: "74.66667",
        country_code3: "IND",
        geonameid: "1279160",
        place_name: "Ajmer",
        feature_class: "A",
        feature_code: "ADM2",
      },
    },

    {
      word: "Johari Bazaar",
      spans: [{ start: 733, end: 746 }],
      country_predicted: "GEO",
      country_conf: 0.24821267,
      geo: {
        admin1: "Rajasthan",
        lat: "26.9211",
        lon: "75.8279",
        country_code3: "IND",
        geonameid: "10276765",
        place_name: "Crowne Plaza Jaipur Tonk Road",
        feature_class: "S",
        feature_code: "HTL",
      },
    },
    {
      word: "Tonk Road",
      spans: [{ start: 935, end: 944 }],
      country_predicted: "IND",
      country_conf: 0.90487736,
      geo: {
        admin1: "Rajasthan",
        lat: "26.77989",
        lon: "75.82773",
        country_code3: "IND",
        geonameid: "10276765",
        place_name: "Crowne Plaza Jaipur Tonk Road",
        feature_class: "S",
        feature_code: "HTL",
      },
    },
    {
      word: "Kalwar Road",
      spans: [{ start: 992, end: 1003 }],
      country_predicted: "IND",
      country_conf: 0.90487736,
      geo: {
        admin1: "Rajasthan",
        lat: "26.9596",
        lon: "75.6709",
        country_code3: "IND",
        geonameid: "10941336",
        place_name: "Karwār Road",
        feature_class: "R",
        feature_code: "RD",
      },
    },
  ],
  "Two days": [
    {
      word: "Pratap Nagar",
      spans: [{ start: 49, end: 69 }],
      country_predicted: "LKA",
      country_conf: 0.24821267,
      geo: {
        admin1: "Rajasthan",
        lat: "26.8037",
        lon: "75.8085",
        country_code3: "IND",
        geonameid: "7302171",
        place_name: "Pratap Nagar",
        feature_class: "P",
        feature_code: "PPL",
      },
    },
    {
      word: "Vaishali Nagar",
      spans: [{ start: 300, end: 314 }],
      country_predicted: "IND",
      country_conf: 0.9637409,
      geo: {
        admin1: "Rajasthan",
        lat: "26.91258",
        lon: "75.74412",
        country_code3: "IND",
        geonameid: "7302171",
        place_name: "Vaishali Nagar",
        feature_class: "P",
        feature_code: "PPL",
      },
    },
    {
      word: "Kanpur",
      spans: [{ start: 1349, end: 1355 }],
      country_predicted: "IND",
      country_conf: 0.9637409,
      geo: {
        admin1: "Uttar Pradesh",
        lat: "26.38052",
        lon: "80.21578",
        country_code3: "IND",
        geonameid: "1267997",
        place_name: "Kānpur",
        feature_class: "A",
        feature_code: "ADM2",
      },
    },

    {
      word: "Delhi",
      spans: [{ start: 1790, end: 1795 }],
      country_predicted: "IND",
      country_conf: 0.95718795,
      geo: {
        admin1: "NCT",
        lat: "28.65195",
        lon: "77.23149",
        country_code3: "IND",
        geonameid: "1273294",
        place_name: "Delhi",
        feature_class: "P",
        feature_code: "PPLA",
      },
    },
  ],
  "Dengue h": [
    {
      word: "Durgapura",
      spans: [{ start: 656, end: 665 }],
      country_predicted: "IND",
      country_conf: 0.9528109,
      geo: {
        admin1: "Rajasthan",
        lat: "26.8518",
        lon: "75.7862",
        country_code3: "IND",
        geonameid: "1272175",
        place_name: "Durgapur",
        feature_class: "P",
        feature_code: "PPL",
      },
    },
    {
      word: "Jamwaramgarh",
      spans: [{ start: 684, end: 696 }],
      country_predicted: "",
      country_conf: 0,
    },
    {
      word: "Pink City",
      spans: [{ start: 1351, end: 1360 }],
      country_predicted: "IND",
      country_conf: 0.90487736,
      geo: {
        admin1: "Arkansas",
        lat: "26.9124",
        lon: "75.7873",
        country_code3: "USA",
        geonameid: "7170063",
        place_name: "Jaipur",
        feature_class: "A",
        feature_code: "ADMD",
      },
    },
    {
      word: "Sanganer",
      spans: [{ start: 1496, end: 1504 }],
      country_predicted: "IND",
      country_conf: 0.9528109,
      geo: {
        admin1: "Rajasthan",
        lat: "26.81459",
        lon: "75.77314",
        country_code3: "IND",
        geonameid: "10735291",
        place_name: "Sanganer Town Railroad Station",
        feature_class: "S",
        feature_code: "RSTN",
      },
    },
    {
      word: "Tonk Road/Sodala",
      spans: [{ start: 1566, end: 1582 }],
      country_predicted: "IND",
      country_conf: 0.24821267,
      geo: {
        admin1: "Rajasthan",
        lat: "26.229376",
        lon: "75.780945",
        country_code3: "IND",
        geonameid: "10735291",
        place_name: "Tonk Road",
        feature_class: "S",
        feature_code: "RSTN",
      },
    },
    {
      word: "Walled City",
      spans: [{ start: 1997, end: 2008 }],
      country_predicted: "IND",
      country_conf: 0.28868943,
      geo: {
        admin1: "Rajasthan",
        lat: "26.922070",
        lon: "75.778885",
        country_code3: "IND",
        geonameid: "10735291",
        place_name: "Walled City",
        feature_class: "S",
        feature_code: "RSTN",
      },
    },
  ],
};
